language: python
cache: pip
env: OMP_NUM_THREADS=4
install:
  - pip install -U pip
  - pip install -U -r requirements.txt
  - python setup.py build_ext --inplace
script:
  - python travis.py
  - python setup.py build_sphinx

